version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx_lebiscuit
    ports:
      - "7020:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    networks:
      - laravel

  db:
    image: postgres:14
    restart: unless-stopped
    container_name: db_lebiscuit
    environment:
      POSTGRES_PASSWORD: "lebiscuit"
      POSTGRES_DB: lebiscuit
    ports:
      - '5440:5432'
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_lebiscuit
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "9004:9004"
    networks:
      - laravel

  composer:
    image: composer:latest
    restart: unless-stopped
    container_name: composer_lebiscuit
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_lebiscuit
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
