version: '3'

services:
  laravel:
    container_name: intention_laravel
    working_dir: /var/www/intention
    depends_on:
      - mysql
    build:
      context: ./intention/
      dockerfile: ./.docker/laravel/Dockerfile
    volumes:
      - ./intention:/var/www/intention
    networks:
      - app-network
  
  lumen:
    container_name: product_lumen
    working_dir: /var/www/product
    build:
      context: ./product/
      dockerfile: ./.docker/lumen/Dockerfile
    volumes:
      - ./product:/var/www/product
    networks:
      - app-network

  nginx:
    container_name: gateway_nginx
    image: nginx:alpine
    depends_on:
      - laravel
      - lumen
    ports:
      - 80:80
      - 430:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - app-network

  mysql:
    container_name: intention_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: intention
      MYSQL_USER: intention_admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./intention/.docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./:/var/www/intention
    networks:
      - app-network

  phpmyadmin:
    container_name: intention_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local


