version: '3'

services:
  nest:
    container_name: product_nest
    working_dir: /var/www/product
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/product
    networks:
      - app-network
    command: npm run start:dev
    ports:
      - 127.0.0.1:3000:3000

networks:
  app-network:
    driver: bridge